project: 
  type: website

website:
  title: "Adam Middleton - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/mid-adamj/real250
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Adam Middleton 2025©"
    right: 
      - icon: linkedin
        href: www.linkedin.com/in/adam-middleton-377229292

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Data Cleansing"
        file: cleansing.qmd
      - text: "Data Exploration"
        file: exploration.qmd
      - text: "Story Telling"
        file: story_telling.qmd
      - text: "Machine Learning"
        file: ml.qmd
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "Competition"
        file: competition.qmd
  
  # learn more about navigation here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Data Cleansing"
      style: "docked"
      background: light
      contents:
        - text: "Data Cleansing"
          file: cleansing.qmd
        - text: "---"
        - text: "Template 1 - Data Processing"
          file: Cleansing_Projects/project1.qmd
        - text: "---"
        - text: "Template 2 - Data Preparation"
          file: Cleansing_Projects/project2.qmd
        - text: "---"
        - text: "Template 3 - Data Formatting"
          file: Cleansing_Projects/project3.qmd
        - text: "---"
        - text: "Template 4 - Data Validation"
          file: Cleansing_Projects/project4.qmd
        - text: "---"
        - text: "Template 5 - Data Analysis"
          file: Cleansing_Projects/project5.qmd
        - text: "---"
    - title: "Data Exploration"
      style: "docked"
      background: light
      contents:
        - text: "Data Exploration"
          file: exploration.qmd
        - text: "---"
        - text: "Project 1"
          file: Exploration_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Exploration_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Exploration_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Exploration_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Exploration_Projects/project5.qmd
        - text: "---"
    - title: "Story Telling"
      style: "docked"
      background: light
      contents:
        - text: "Story Telling"
          file: story_telling.qmd
        - text: "---"
        - text: "Project 1"
          file: Story_Telling/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Story_Telling/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Story_Telling/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Story_Telling/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Story_Telling/project5.qmd
        - text: "---"
    - title: "Machine Learning"
      style: "docked"
      background: light
      contents:
        - text: "Machine Learning"
          file: ml.qmd
        - text: "---"
        - text: "Project 1"
          file: Machine_Learning/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Machine_Learning/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Machine_Learning/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Machine_Learning/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Machine_Learning/project5.qmd
        - text: "---"
    - title: "Full Stack"
      style: "docked"
      background: light
      contents:
        - text: "Full Stack"
          file: full_stack.qmd
        - text: "---"
        - text: "Project 1"
          file: Full_Stack/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Full_Stack/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Full_Stack/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Full_Stack/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Full_Stack/project5.qmd
        - text: "---"
    - title: "Competition"
      style: "docked"
      background: light
      contents:
        - text: "Competition"
          file: competition.qmd
        - text: "---"
        - text: "Project 1"
          file: Competition/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Competition/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Competition/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Competition/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Competition/project5.qmd
        - text: "---"

format:  
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


