---
layout: cv
title: Adam Middleton's Resume
---
# Adam Middleton
- Student of Biology

<div id="webaddress">
<a href="ajmiddle10@gmail.com">ajmiddle10@gmail.com</a>
| <a href="https://mid-adamj.github.io/real250/">Portfolio Website</a>
</div>


## Currently

Student at Brigham Young University-Idaho 

### Majoring in

Biology

### Research interests

Genetics, Data Science


## Education

`Sept 2023 - now`
__Brigham Young University-Idaho__
Rexburg, ID

## Occupation

`Cashier`

`Jun. 2021 – Aug. 2021`
__Harris Teeter: Groceries and Pharmacy__, Chantilly, VA

- Handled sales transactions, operated the cash register, and provided excellent customer service.
- Communicated effectively with customers, creating a friendly environment. 
- Fostered a sense of diligence, especially during rush hours of the day.
- Procured a more complete understanding of patience with others. 

## Volunteer Work
`Full-Time Volunteer Representative`
__The Church of Jesus Christ of Latter-day Saints__, Fort Lauderdale, FL

- Served as a missionary, teaching prospective converts.
- Taught English to Latin American immigrants. 
- Contributed time to community service projects and planned local church service projects. 
- Achieved advanced proficiency in Spanish through intensive study and practice.  
- Honed communication and collaboration skills while serving with other missionaries and authority figures.
- Developed problem-solving abilities through weekly goal-setting and feedback sessions.  

## Other
- Laboratory Skills: Experience in plating bacteria and testing for antibiotic production; familiarity with common laboratory equipment.
- Foundational knowledge and some experience coding in the Python and R languages.

<!-- ### Footer
Last updated: May 2013 -->